from pathlib import Path
p = Path(r'c:\Users\mdf37\offline_attendance\lib\main.dart')
lines = p.read_text(encoding='utf-8').splitlines()

# Replace analytics tab block
analytics_start = next(i for i,l in enumerate(lines) if l.strip() == 'Widget _buildAnalyticsTab(')
analytics_end = next(i for i,l in enumerate(lines) if l.strip() == 'Widget _buildInsightRowCustom(')
analytics_replacement = [
  '  Widget _buildAnalyticsTab(',
  '    Color cardColor,',
  '    Color textColor,',
  '    Color subTextColor,',
  '    Color highlightBg,',
  '    int targetPerc,',
  '  ) {',
  '    final now = DateTime.now();',
  '    final daysInMonth = DateTime(now.year, now.month + 1, 0).day;',
  '    int totalAbsent = _totalClasses - _totalPresent;',
  '    int overallPercent = _totalClasses == 0',
  '        ? 0',
  '        : ((_totalPresent / _totalClasses) * 100).toInt();',
  '',
  '    final uniqueSubjects = _subjectsList',
  '        .map((subject) => subject["subject"]!)',
  '        .toSet()',
  '        .toList();',
  '',
  '    final activeSubjects = <Map<String, dynamic>>[];',
  '    for (var subjectName in uniqueSubjects) {',
  '      int sTotal = 0;',
  '      int sPresent = 0;',
  '      _cardIsLocked.forEach((key, isLocked) {',
  '        if (isLocked && key.startsWith(\'$subjectName\'_\')) {',
  '          sTotal++;',
  '          if (_cardAttendanceStatus[key] == \'Present\') {',
  '            sPresent++;',
  '          }',
  '        }',
  '      });',
  '      if (sTotal > 0) {',
  '        activeSubjects.add({',
  '          \'name\': subjectName,',
  '          \'total\': sTotal,',
  '          \'present\': sPresent,',
  '          \'perc\': ((sPresent / sTotal) * 100).toInt(),',
  '        });',
  '      }',
  '    }',
  '',
  '    activeSubjects.sort(',
  '      (a, b) => (b[\'perc\'] as int).compareTo(a[\'perc\'] as int),',
  '    );',
  '',
  '    final Map<String, dynamic>? highestSub =',
  '        activeSubjects.isNotEmpty ? activeSubjects.first : null;',
  '    final Map<String, dynamic>? lowestSub =',
  '        activeSubjects.isNotEmpty ? activeSubjects.last : null;',
  '',
  '    Map<String, dynamic>? warningSub;',
  '    for (var subject in activeSubjects) {',
  '      if ((subject[\'perc\'] as int) < targetPerc) {',
  '        warningSub = subject;',
  '        break;',
  '      }',
  '    }',
  '',
  '    final attendanceByDate = <DateTime, bool>{};',
  '    for (var date in _presentDates) {',
  '      attendanceByDate[DateTime(date.year, date.month, date.day)] = true;',
  '    }',
  '    for (var date in _absentDates) {',
  '      attendanceByDate[DateTime(date.year, date.month, date.day)] = false;',
  '    }',
  '',
  '    final sortedDates = attendanceByDate.keys.toList()..sort();',
  '    int longestStreak = 0;',
  '    int currentStreak = 0;',
  '    int streak = 0;',
  '    DateTime? previousDate;',
  '',
  '    for (var date in sortedDates) {',
  '      if (attendanceByDate[date] == true) {',
  '        if (previousDate != null && date.difference(previousDate).inDays == 1) {',
  '          streak++;',
  '        } else {',
  '          streak = 1;',
  '        }',
  '        if (streak > longestStreak) longestStreak = streak;',
  '      } else {',
  '        streak = 0;',
  '      }',
  '      previousDate = date;',
  '    }',
  '',
  '    if (sortedDates.isNotEmpty) {',
  '      DateTime pointer = sortedDates.last;',
  '      while (attendanceByDate[pointer] == true) {',
  '        currentStreak++;',
  '        pointer = pointer.subtract(const Duration(days: 1));',
  '      }',
  '    }',
  '',
  '    final weekdayStats = {',
  '      DateTime.monday: {\'present\': 0, \'total\': 0},',
  '      DateTime.tuesday: {\'present\': 0, \'total\': 0},',
  '      DateTime.wednesday: {\'present\': 0, \'total\': 0},',
  '      DateTime.thursday: {\'present\': 0, \'total\': 0},',
  '      DateTime.friday: {\'present\': 0, \'total\': 0},',
  '      DateTime.saturday: {\'present\': 0, \'total\': 0},',
  '    };',
  '',
  '    attendanceByDate.forEach((date, present) {',
  '      if (weekdayStats.containsKey(date.weekday)) {',
  '        weekdayStats[date.weekday]!['present'] =',
  '            weekdayStats[date.weekday]!['present']! + 1;',
  '        weekdayStats[date.weekday]!['total'] =',
  '            weekdayStats[date.weekday]!['total']! + 1;',
  '      }',
  '    });',
  '',
  '    int getDayPerc(int weekday) {',
  '      final totals = weekdayStats[weekday]!['total']!;',
  '      final present = weekdayStats[weekday]!['present']!;',
  '      return totals == 0 ? 0 : ((present / totals) * 100).toInt();',
  '    }',
  '',
  '    return ListView(',
  '      padding: const EdgeInsets.fromLTRB(20, 50, 20, 110),',
  '      physics: const BouncingScrollPhysics(),',
  '      children: [',
  '        Row(',
  '          mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '          children: [',
  '            Text(',
  '              "Analytics",',
  '              style: TextStyle(',
  '                fontSize: 34,',
  '                fontWeight: FontWeight.w900,',
  '                color: textColor,',
  '              ),',
  '            ),',
  '            GestureDetector(',
  '              onTap: () => _showGeminiSettingsModal(cardColor, textColor),',
  '              child: Container(',
  '                padding: const EdgeInsets.all(10),',
  '                decoration: BoxDecoration(',
  '                  color: cardColor,',
  '                  shape: BoxShape.circle,',
  '                  boxShadow: [',
  '                    BoxShadow(',
  '                      color: Colors.black.withValues(alpha: 0.05),',
  '                      blurRadius: 10,',
  '                    ),',
  '                  ],',
  '                ),',
  '                child: const Icon(',
  '                  Icons.settings_outlined,',
  '                  color: Color(0xFF2A9D8F),',
  '                  size: 24,',
  '                ),',
  '              ),',
  '            ),',
  '          ],',
  '        ),',
  '        const SizedBox(height: 25),',
  '        GridView.count(',
  '          crossAxisCount: 2,',
  '          shrinkWrap: true,',
  '          physics: const NeverScrollableScrollPhysics(),',
  '          childAspectRatio: 2.2,',
  '          crossAxisSpacing: 15,',
  '          mainAxisSpacing: 15,',
  '          children: [',
  '            _miniBubbleCard(',
  '              "Current %",',
  '              "$overallPercent%",',
  '              const Color(0xFF2A9D8F),',
  '              cardColor,',
  '            ),',
  '            _miniBubbleCard(',
  '              "Required",',
  '              "$targetPerc%",',
  '              Colors.orange,',
  '              cardColor,',
  '            ),',
  '            _miniBubbleCard(',
  '              "Total Present",',
  '              "$_totalPresent",',
  '              textColor,',
  '              cardColor,',
  '            ),',
  '            _miniBubbleCard(',
  '              "Total Absent",',
  '              "$totalAbsent",',
  '              Colors.red,',
  '              cardColor,',
  '            ),',
  '          ],',
  '        ),',
  '        const SizedBox(height: 35),',
  '        if (activeSubjects.isNotEmpty) ...[',
  '          Padding(',
  '            padding: const EdgeInsets.only(left: 10, bottom: 15),',
  '            child: Text(',
  '              "Safe Calculator",',
  '              style: TextStyle(',
  '                fontWeight: FontWeight.w900,',
  '                fontSize: 20,',
  '                color: textColor,',
  '              ),',
  '            ),',
  '          ),',
  '          ...activeSubjects.map((sub) {',
  '            int sTotal = sub[\'total\'] as int;',
  '            int sPresent = sub[\'present\'] as int;',
  '            int sPerc = sub[\'perc\'] as int;',
  '            String statusLabel;',
  '            Color statusColor;',
  '            int missable = 0;',
  '            int needed = 0;',
  '',
  '            if (sPerc >= targetPerc) {',
  '              statusLabel = "Safe ($sPerc%)";',
  '              statusColor = const Color(0xFF2A9D8F);',
  '              missable = ((sPresent * 100) / targetPerc).floor() - sTotal;',
  '              if (missable < 0) missable = 0;',
  '            } else {',
  '              statusLabel = sPerc <= targetPerc - 10',
  '                  ? "Danger ($sPerc%)"',
  '                  : "Warning ($sPerc%)";',
  '              statusColor = sPerc <= targetPerc - 10',
  '                  ? Colors.red',
  '                  : Colors.orange.shade700;',
  '              needed =',
  '                  ((targetPerc * sTotal - 100 * sPresent) / (100 - targetPerc))',
  '                      .ceil();',
  '              if (needed < 0) needed = 0;',
  '            }',
  '            return _buildSafeCalcBubble(',
  '              sub[\'name\'] as String,',
  '              statusLabel,',
  '              missable.toString(),',
  '              needed.toString(),',
  '              statusColor,',
  '              cardColor,',
  '              textColor,',
  '            );',
  '          }),',
  '          const SizedBox(height: 25),',
  '        ],',
  '        if (highestSub != null && lowestSub != null) ...[',
  '          Padding(',
  '            padding: const EdgeInsets.only(left: 10, bottom: 15),',
  '            child: Text(',
  '              "Subject Ranking",',
  '              style: TextStyle(',
  '                fontWeight: FontWeight.w900,',
  '                fontSize: 20,',
  '                color: textColor,',
  '              ),',
  '            ),',
  '          ),',
  '          Row(',
  '            children: [',
  '              Expanded(',
  '                child: _buildRankingBubble(',
  '                  "Highest",',
  '                  highestSub[\'name\'] as String,',
  '                  "${highestSub[\'perc\']}%",',
  '                  Icons.emoji_events,',
  '                  const Color(0xFF2A9D8F),',
  '                  cardColor,',
  '                  textColor,',
  '                ),',
  '              ),',
  '              const SizedBox(width: 15),',
  '              Expanded(',
  '                child: _buildRankingBubble(',
  '                  "Lowest",',
  '                  lowestSub[\'name\'] as String,',
  '                  "${lowestSub[\'perc\']}%",',
  '                  Icons.warning,',
  '                  Colors.red,',
  '                  cardColor,',
  '                  textColor,',
  '                ),',
  '              ),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 35),',
  '        ],',
  '        if (activeSubjects.isNotEmpty) ...[',
  '          Padding(',
  '            padding: const EdgeInsets.only(left: 10, bottom: 15),',
  '            child: Text(',
  '              "Insights Section",',
  '              style: TextStyle(',
  '                fontWeight: FontWeight.w900,',
  '                fontSize: 20,',
  '                color: textColor,',
  '              ),',
  '            ),',
  '          ),',
  '          Container(',
  '            padding: const EdgeInsets.symmetric(horizontal: 25, vertical: 25),',
  '            decoration: BoxDecoration(',
  '              color: highlightBg,',
  '              borderRadius: BorderRadius.circular(30),',
  '              border: Border.all(',
  '                color: const Color(0xFF2A9D8F).withValues(alpha: 0.3),',
  '                width: 1.5,',
  '              ),',
  '              boxShadow: [',
  '                BoxShadow(',
  '                  color: const Color(0xFF2A9D8F).withValues(alpha: 0.05),',
  '                  blurRadius: 20,',
  '                  offset: const Offset(0, 10),',
  '                ),',
  '              ],',
  '            ),',
  '            child: Column(',
  '              children: [',
  '                if (highestSub != null)',
  '                  _buildInsightRowCustom(',
  '                    Icons.auto_awesome,',
  '                    const Color(0xFF2A9D8F),',
  '                    "Your best attendance is in ${highestSub[\'name\']} (${highestSub[\'perc\']}%).",',
  '                    subTextColor,',
  '                  ),',
  '                if (highestSub != null) const SizedBox(height: 18),',
  '                if (lowestSub != null)',
  '                  _buildInsightRowCustom(',
  '                    Icons.error,',
  '                    Colors.orange,',
  '                    "Your lowest attendance is in ${lowestSub[\'name\']} (${lowestSub[\'perc\']}%).",',
  '                    subTextColor,',
  '                  ),',
  '                if (lowestSub != null) const SizedBox(height: 18),',
  '                if (warningSub != null)',
  '                  _buildInsightRowCustom(',
  '                    Icons.info,',
  '                    const Color(0xFF2A9D8F),',
  '                    "You need ${((targetPerc * (warningSub[\'total\'] as int) - 100 * (warningSub[\'present\'] as int)) / (100 - targetPerc)).ceil()} consecutive classes in ${warningSub[\'name\']} to reach $targetPerc%.",',
  '                    subTextColor,',
  '                  )',
  '                else',
  '                  _buildInsightRowCustom(',
  '                    Icons.info,',
  '                    const Color(0xFF2A9D8F),',
  '                    "Keep it up! You are maintaining the target of $targetPerc% across all active subjects.",',
  '                    subTextColor,',
  '                  ),',
  '              ],',
  '            ),',
  '          ),',
  '          const SizedBox(height: 35),',
  '        ],',
  '        Padding(',
  '          padding: const EdgeInsets.only(left: 10, bottom: 15),',
  '          child: Text(',
  '            "Streak",',
  '            style: TextStyle(',
  '              fontWeight: FontWeight.w900,',
  '              fontSize: 20,',
  '              color: textColor,',
  '            ),',
  '          ),',
  '        ),',
  '        _buildBubbleCard(',
  '          cardColor,',
  '          child: Padding(',
  '            padding: const EdgeInsets.symmetric(vertical: 10),',
  '            child: Row(',
  '              mainAxisAlignment: MainAxisAlignment.spaceEvenly,',
  '              children: [',
  '                _streakStat(',
  '                  "$currentStreak",',
  '                  "Current",',
  '                  const Color(0xFF2A9D8F),',
  '                ),',
  '                Container(',
  '                  width: 1,',
  '                  height: 40,',
  '                  color: Colors.grey.withValues(alpha: 0.2),',
  '                ),',
  '                _streakStat(',
  '                  "$longestStreak",',
  '                  "Longest",',
  '                  const Color(0xFF2A9D8F),',
  '                ),',
  '                Container(',
  '                  width: 1,',
  '                  height: 40,',
  '                  color: Colors.grey.withValues(alpha: 0.2),',
  '                ),',
  '                _streakStat("${_absentDates.length}", "Absent", Colors.red),',
  '              ],',
  '            ),',
  '          ),',
  '        ),',
  '        const SizedBox(height: 35),',
  '        Padding(',
  '          padding: const EdgeInsets.only(left: 10, bottom: 15),',
  '          child: Text(',
  '            "Weekly Analysis",',
  '            style: TextStyle(',
  '              fontWeight: FontWeight.w900,',
  '              fontSize: 20,',
  '              color: textColor,',
  '            ),',
  '          ),',
  '        ),',
  '        _buildBubbleCard(',
  '          cardColor,',
  '          child: SizedBox(',
  '            height: 240,',
  '            child: Row(',
  '              mainAxisAlignment: MainAxisAlignment.spaceEvenly,',
  '              crossAxisAlignment: CrossAxisAlignment.end,',
  '              children: [',
  '                _buildPillBar("Mon", getDayPerc(DateTime.monday), getDayPerc(DateTime.monday) >= targetPerc ? const Color(0xFF2A9D8F) : Colors.orange, textColor),',
  '                _buildPillBar("Tue", getDayPerc(DateTime.tuesday), getDayPerc(DateTime.tuesday) >= targetPerc ? const Color(0xFF2A9D8F) : Colors.orange, textColor),',
  '                _buildPillBar("Wed", getDayPerc(DateTime.wednesday), getDayPerc(DateTime.wednesday) >= targetPerc ? const Color(0xFF2A9D8F) : Colors.orange, textColor),',
  '                _buildPillBar("Thu", getDayPerc(DateTime.thursday), getDayPerc(DateTime.thursday) >= targetPerc ? const Color(0xFF2A9D8F) : Colors.orange, textColor),',
  '                _buildPillBar("Fri", getDayPerc(DateTime.friday), getDayPerc(DateTime.friday) >= targetPerc ? const Color(0xFF2A9D8F) : Colors.orange, textColor),',
  '                _buildPillBar("Sat", getDayPerc(DateTime.saturday), getDayPerc(DateTime.saturday) >= targetPerc ? const Color(0xFF2A9D8F) : Colors.orange, textColor),',
  '              ],',
  '            ),',
  '          ),',
  '        ),',
  '        const SizedBox(height: 35),',
  '        _buildBubbleCard(',
  '          cardColor,',
  '          child: Column(',
  '            children: [',
  '              Row(',
  '                mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '                children: [',
  '                  Text(',
  '                    "Calendar",',
  '                    style: TextStyle(',
  '                      fontWeight: FontWeight.w900,',
  '                      fontSize: 20,',
  '                      color: textColor,',
  '                    ),',
  '                  ),',
  '                  Row(',
  '                    children: [',
  '                      Container(',
  '                        padding: const EdgeInsets.all(4),',
  '                        decoration: BoxDecoration(',
  '                          color: Colors.grey.withValues(alpha: 0.1),',
  '                          shape: BoxShape.circle,',
  '                        ),',
  '                        child: const Icon(Icons.chevron_left, size: 18),',
  '                      ),',
  '                      const SizedBox(width: 8),',
  '                      Text(',
  '                        "${_monthName(now.month)} ${now.year}",',
  '                        style: const TextStyle(',
  '                          fontWeight: FontWeight.bold,',
  '                          color: Color(0xFF2A9D8F),',
  '                        ),',
  '                      ),',
  '                      const SizedBox(width: 8),',
  '                      Container(',
  '                        padding: const EdgeInsets.all(4),',
  '                        decoration: BoxDecoration(',
  '                          color: Colors.grey.withValues(alpha: 0.1),',
  '                          shape: BoxShape.circle,',
  '                        ),',
  '                        child: const Icon(Icons.chevron_right, size: 18),',
  '                      ),',
  '                    ],',
  '                  ),',
  '                ],',
  '              ),',
  '              const SizedBox(height: 25),',
  '              GridView.builder(',
  '                shrinkWrap: true,',
  '                physics: const NeverScrollableScrollPhysics(),',
  '                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(',
  '                  crossAxisCount: 7,',
  '                  crossAxisSpacing: 10,',
  '                  mainAxisSpacing: 10,',
  '                ),',
  '                itemCount: daysInMonth,',
  '                itemBuilder: (context, index) {',
  '                  int day = index + 1;',
  '                  final date = DateTime(now.year, now.month, day);',
  '                  final status = attendanceByDate[date];',
  '                  Color bgColor;',
  '                  if (status == true) {',
  '                    bgColor = const Color(0xFF2A9D8F);',
  '                  } else if (status == false) {',
  '                    bgColor = Colors.red;',
  '                  } else {',
  '                    bgColor = Colors.grey.withValues(alpha: 0.2);',
  '                  }',
  '',
  '                  return Container(',
  '                    decoration: BoxDecoration(',
  '                      color: bgColor,',
  '                      shape: BoxShape.circle,',
  '                      boxShadow: bgColor != Colors.grey.withValues(alpha: 0.2)',
  '                          ? [',
  '                              BoxShadow(',
  '                                color: bgColor.withValues(alpha: 0.3),',
  '                                blurRadius: 8,',
  '                                offset: const Offset(0, 3),',
  '                              ),',
  '                            ]',
  '                          : null,',
  '                    ),',
  '                    child: Center(',
  '                      child: Text(',
  '                        "$day",',
  '                        style: TextStyle(',
  '                          color: bgColor == Colors.grey.withValues(alpha: 0.2)',
  '                              ? textColor',
  '                              : Colors.white,',
  '                          fontWeight: FontWeight.bold,',
  '                          fontSize: 13,',
  '                        ),',
  '                      ),',
  '                    ),',
  '                  );',
  '                },',
  '              ),',
  '              const SizedBox(height: 25),',
  '              Row(',
  '                mainAxisAlignment: MainAxisAlignment.center,',
  '                children: [',
  '                  _legendDot(const Color(0xFF2A9D8F), "Present", textColor),',
  '                  const SizedBox(width: 20),',
  '                  _legendDot(Colors.red, "Absent", textColor),',
  '                  const SizedBox(width: 20),',
  '                  _legendDot(',
  '                    Colors.grey.withValues(alpha: 0.3),',
  '                    "No Class",',
  '                    textColor,',
  '                  ),',
  '                ],',
  '              ),',
  '            ],',
  '          ),',
  '        ),',
  '      ],',
  '    );',
  '  }',
  '',
  '  String _monthName(int month) {',
  '    const names = [',
  "      'January',",',
  "      'February',",',
  "      'March',",',
  "      'April',",',
  "      'May',",',
  "      'June',",',
  "      'July',",',
  "      'August',",',
  "      'September',",',
  "      'October',",',
  "      'November',",',
  "      'December',",',
  '    ];',
  '    return names[month - 1];',
  '  }',
  '',
]
lines[analytics_start:analytics_end] = analytics_replacement

# Replace broken helpers block
streak_start = next(i for i,l in enumerate(lines) if 'Widget _streakStat(' in l)
profile_start = next(i for i,l in enumerate(lines) if 'Widget _buildProfileInfoBubble(' in l)
helper_replacement = [
  '  Widget _streakStat(String value, String label, Color color) {',
  '    return Column(',
  '      children: [',
  '        Text(',
  '          value,',
  '          style: TextStyle(',
  '            fontSize: 28,',
  '            fontWeight: FontWeight.w900,',
  '            color: color,',
  '          ),',
  '        ),',
  '        const SizedBox(height: 5),',
  '        Text(',
  '          label,',
  '          style: const TextStyle(',
  '            fontSize: 12,',
  '            fontWeight: FontWeight.bold,',
  '            color: Colors.grey,',
  '          ),',
  '        ),',
  '      ],',
  '    );',
  '  }',
  '',
  '  Widget _buildSafeCalcBubble(',
  '    String subject,',
  '    String statusLabel,',
  '    String missable,',
  '    String toReach,',
  '    Color statusColor,',
  '    Color cardColor,',
  '    Color textColor,',
  '  ) {',
  '    return Container(',
  '      margin: const EdgeInsets.only(bottom: 15),',
  '      padding: const EdgeInsets.all(20),',
  '      decoration: BoxDecoration(',
  '        color: cardColor,',
  '        borderRadius: BorderRadius.circular(30),',
  '        boxShadow: [',
  '          BoxShadow(',
  '            color: Colors.black.withValues(alpha: 0.04),',
  '            blurRadius: 20,',
  '            offset: const Offset(0, 10),',
  '          ),',
  '        ],',
  '      ),',
  '      child: Column(',
  '        crossAxisAlignment: CrossAxisAlignment.start,',
  '        children: [',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  '              Expanded(',
  '                child: Text(',
  '                  subject,',
  '                  maxLines: 1,',
  '                  overflow: TextOverflow.ellipsis,',
  '                  style: TextStyle(',
  '                    fontWeight: FontWeight.w900,',
  '                    fontSize: 18,',
  '                    color: textColor,',
  '                  ),',
  '                ),',
  '              ),',
  '              Container(',
  '                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),',
  '                decoration: BoxDecoration(',
  '                  color: statusColor.withValues(alpha: 0.1),',
  '                  borderRadius: BorderRadius.circular(20),',
  '                ),',
  '                child: Text(',
  '                  statusLabel,',
  '                  style: TextStyle(',
  '                    color: statusColor,',
  '                    fontWeight: FontWeight.w900,',
  '                    fontSize: 13,',
  '                  ),',
  '                ),',
  '              ),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 15),',
  '          Text(',
  '            "Missable Classes: $missable",',
  '            style: TextStyle(',
  '              fontSize: 14,',
  '              fontWeight: FontWeight.w600,',
  '              color: missable == "0" ? Colors.grey : const Color(0xFF2A9D8F),',
  '            ),',
  '          ),',
  '          if (toReach != "0")',
  '            Padding(',
  '              padding: const EdgeInsets.only(top: 5),',
  '              child: Text(',
  '                "To Reach Target: $toReach classes",',
  '                style: const TextStyle(',
  '                  fontSize: 14,',
  '                  fontWeight: FontWeight.w600,',
  '                  color: Colors.red,',
  '                ),',
  '              ),',
  '            ),',
  '        ],',
  '      ),',
  '    );',
  '  }',
  '',
  '  Widget _buildRankingBubble(',
  '    String label,',
  '    String subject,',
  '    String percent,',
  '    IconData icon,',
  '    Color color,',
  '    Color cardColor,',
  '    Color textColor,',
  '  ) {',
  '    return _buildBubbleCard(',
  '      cardColor,',
  '      child: Column(',
  '        crossAxisAlignment: CrossAxisAlignment.center,',
  '        children: [',
  '          Container(',
  '            padding: const EdgeInsets.all(10),',
  '            decoration: BoxDecoration(',
  '              color: color.withValues(alpha: 0.1),',
  '              shape: BoxShape.circle,',
  '            ),',
  '            child: Icon(icon, size: 24, color: color),',
  '          ),',
  '          const SizedBox(height: 15),',
  '          Text(',
  '            label,',
  '            style: const TextStyle(',
  '              fontSize: 12,',
  '              fontWeight: FontWeight.bold,',
  '              color: Colors.grey,',
  '            ),',
  '          ),',
  '          const SizedBox(height: 5),',
  '          Text(',
  '            subject,',
  '            maxLines: 1,',
  '            overflow: TextOverflow.ellipsis,',
  '            style: TextStyle(',
  '              fontSize: 16,',
  '              fontWeight: FontWeight.w900,',
  '              color: textColor,',
  '            ),',
  '          ),',
  '          const SizedBox(height: 5),',
  '          Text(',
  '            percent,',
  '            maxLines: 1,',
  '            overflow: TextOverflow.ellipsis,',
  '            style: TextStyle(',
  '              fontSize: 28,',
  '              fontWeight: FontWeight.w900,',
  '              color: color,',
  '            ),',
  '          ),',
  '        ],',
  '      ),',
  '    );',
  '  }',
  '',
]
lines[streak_start:profile_start] = helper_replacement

p.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('replaced')
